openapi: 3.1.0
info:
  title: P2P framework
  version: 0.2
paths:
  /:key:
    get:
      summary: Get an entry from hash table
      description: data is an array
      parameters:
      - name: key
        in: path
      responses:
        "200":
          description: OK
          content:
            schema:
              format:
                error: "boolean"
                errorMsg: "string"
                key: "string"
                data: "any[]"
              example:
                error: false
                errorMsg: null
                key: "Grundgesetz"
                data: [ "postingList1", "postingList2" ]
        "400":
          description: User error
          content:
            schema:
              format:
                error: "boolean"
                errorMsg: "string"
                key: "string"
                data: "any[]"
              example:
                error: true
                errorMsg: "No key given"
                key: null
                data: null
    put:
      summary: Insert an entry into the hash table (replace if exists)
      description: data shall be an array, if it is not it will be wrapped in one
      parameters:
      - name: key
        in: path
      - name: data
        in: body
        schema:
          format:
            data: "any[]"
      responses:
        "200":
          description: OK
          content:
            schema:
              format:
                error: "boolean"
                errorMsg: "string"
                key: "string"
              example:
                error: false
                errorMsg: null
                key: "Grundgesetz"
        "400":
          description: User error
          content:
            schema:
              format:
                error: "boolean"
                errorMsg: "string"
                key: "string"
              example:
                error: true
                errorMsg: "No key given"
                key: null
  /append/:key:
    post:
      summary: Append to an entry in the hash table
      description: data shall be an array (if not it will be encapsulated in one) and will be concatenated with the existing entry if there is one
      parameters:
      - name: key
        in: path
      - name: data
        in: body
        schema:
          format:
            data: "any[]"
      responses:
        "200":
          description: OK
          content:
            schema:
              format:
                error: "boolean"
                errorMsg: "string"
                key: "string"
              example:
                error: false
                errorMsg: null
                key: "Grundgesetz"
        "400":
          description: User error
          content:
            schema:
              format:
                error: "boolean"
                errorMsg: "string"
                key: "string"
              example:
                error: true
                errorMsg: "No key given"
                key: null
  /batch-get:
    post:
      summary: Get multiple entries of the hash table
      description:
        parameters:
          - name: keys
            in: body
            schema:
              format:
                data: "string[]"
        responses:
          "200":
            description: OK
            content:
              schema:
                format:
                  error: "boolean"
                  errorMsg: "string"
                  keys: "string[]"
                  data: "any[][]"
                example:
                  error: false
                  errorMsg: null
                  keys: [ "Grundgesetz", "Merkel" ]
                  data: [ [ "postingList1", "postingList2" ], [ "postingList3", "postingList4" ] ]
          "400":
            description: User error
            content:
              schema:
                format:
                  error: "boolean"
                  errorMsg: "string"
                  keys: "string[]"
                example:
                  error: true
                  errorMsg: "No keys given"
                  keys: null
