#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ -z "$1" ]; then
  cat <<EOF
$ spawnnode NR [-p]
Run a given node

Parameters:
  \$1: number 0-9

Flags:
  -p: print mode
EOF
  exit
fi

N="$1"
export HTTP_PORT="809$N"
export PEER_PORT="807$N"
export PEER_STORAGE="/tmp/storage$N"
export DEBUG=libp2p:dht:Q*,libp2p:dht:rpc:get-value:*
# uses debug package for logging: https://www.npmjs.com/package/debug

if [ "$2" = "-p" ]; then
  npm run addr
else
  npm run start-prod
fi
